export const ActionTypes = {
  GET_ALL_COUNTRIES: "GET_ALL_COUNTRIES",
  SEARCH_COUNTRY: "SEARCH_COUNTRY",
  GET_DETAIL: "GET_DETAIL",
  CREATE_ACTIVITY: "CREATE_ACTIVITY",
  GET_ALL_ACTIVITIES: "GET_ALL_ACTIVITIES",
  DELETE_ACTIVITY: "DELETE_ACTIVITY",
  MODIFY_ACTIVITY: "MODIFY_ACTIVITY",
  FILTERS_VALUE: "FILTERS_VALUE",
  ORDER_VALUE: "ORDER_VALUE",
};

export const f_o = {
  ALL: "ALL",
  ASCENDENTE: "ASCENDENTE",
  DESCENDENTE: "DESCENDENTE",
  Mayor_Poblacion: "Mayor_Poblacion",
  Menor_Poblacion: "Menor_Poblacion",
};
