export const ActionTypes = {
  GET_ALL_COUNTRIES: 'GET_ALL_COUNTRIES',
  SEARCH_COUNTRY: 'SEARCH_COUNTRY',
  FILTER_BY_CONTINENTS: 'FILTER_BY_CONTINENTS',
  FILTER_BY_ACTIVITIES: 'FILTER_BY_ACTIVITIES',
  ORDER_BY_NAME: 'ORDER_BY_NAME',
  ORDER_BY_POPULATION: 'ORDER_BY_POPULATION',
  GET_DETAIL: 'GET_DETAIL',
  CREATE_ACTIVITY: 'CREATE_ACTIVITY',
  GET_ALL_ACTIVITIES: 'GET_ALL_ACTIVITIES',
  DELETE_ACTIVITY: 'DELETE_ACTIVITY',
  MODIFY_ACTIVITY: 'MODIFY_ACTIVITY',
}
